### ISSUE TITLE
New setting: newFile.showPathRelativeTo

### ISSUE THREAD

**Issue by patrickhulce** [dkundel/vscode-new-file#17]
First off, thanks for the plugin it's really is a big benefit to bring back some Atom-like features I've been missing! :)

Instead of the absolute path or just the path relative to the file as options it'd be nice to see the path relative to project root.

Example:

I'm currently editing `deeply/nested/file.js` in a project located at `/project/path`. I'd like to be able to see `deeply/nested/newFile.js` instead of `/project/path/deeply/nested/newFile.js` or `newFile.js`. Keeping it as an setting for preserving current functionality seems like a good idea.

**Comment by dkundel** [comment]
Hey @patrickhulce!

I'll look into this over the weekend and see if I can get an update out quickly :)

**Comment by patrickhulce** [comment]
Awesome that'd be great! :D

**Comment by davidascher** [comment]
Agree with this kind of feature.  In general, I find that 99% of the time I want to create a file very close to a current file, 90% of the time it's in the same directory.

While you're digging in this code, I suggest:

- [ ] at the very least, letting `./newfile.js` work, so that I don't have to worry about editing a full path in the dialog
- [ ] preferably, also let `newfile.js` work.
- [ ] at the very very least ;-), changing the selection on dialog open to be just the filename part of the path, so that the user sequence is `<kbd-shortcut><type-filename><enter>` with no path manipulation keystrokes needed (except when wanted). 

Also thanks for the addon, I was feeling handicapped w/o it.

**Comment by dkundel** [comment]
This option just shipped with v3.0.0. You can use the following values:
- `"newFile.showPathRelativeTo": "root"` --> Basically a replacement of `newFile.showFullPath` which has been deprecated
- `"newFile.showPathRelativeTo": "project"` --> Basically shows the full path but removes the path up to the project root. This in combination with `"newFile.relativeTo": "file"` should give you the exact behavior you wanted
- `"newFile.showPathRelativeTo": "none"` --> Equivalent to `"newFile.showFullPath": false`

I also added support for using `./newfile.js` notation regardless of any configuration as a short cut to create a file relative to the currently open file. I hope that helps @davidascher 

As for the last thing on your list @davidascher, unfortunately this isn't supported by the VS Code API, I would love to be able to choose what is selected in the path. This is the reason why I have so many different configuration options to serve as many needs / wishes as possible.

Please let me know if you would like to see anything else.

Cheers,
Dominik

**Comment by patrickhulce** [comment]
awesome @dkundel works like a charm! thanks for graciously accepting the feedback! 😄  🎉  💯

**Comment by dgunderson** [comment]
Thanks for this feature. I just wanted to point out that there's a misleading comment in the settings that threw me for a loop for a few minutes, as I copy/pasted what was typed there instead of the actual setting:

![image](https://user-images.githubusercontent.com/5771312/28092575-206af886-6651-11e7-9e87-f08dddfc2cd4.png)

Looks like the typo is in the word ```Full```, as that references a setting that does not exist.

Also, it would make sense to have it say:

```JavaScript
// [DEPRECATED] Use newFile.showFullPathRelativeTo: project instead.
```
Since it's showing the default setting of "false" for ```"newFile.showFullPath": false```. That deprecated setting default says "I don't want the full path", and then in the suggestion in the comment above, it says to use "root", which *will* show the full path... that also threw me for a loop until I realized what I wanted was "project".

Not a huge deal but figured it was worth mentioning. Again, thanks for the extension.

**Comment by dkundel** [comment]
Good catch @dgunderson! I fixed it :) I changed the name of the setting half way through implementing it and must have missed this one. 

Your understanding is also correct. When I wrote that comment I had in mind that in order to emulate the setting to be `true` you should use `'root'`. I can see how that's confusing though.
